### ISSUE TITLE
Allow using custom InterfacePrefix value in callico

### ISSUE THREAD

**Issue by cutwater** [projectcalico/libcalico#146]
Currently it is not possible to use custom `InterfacePrefix` value in libcalico, since it is not read from ETCD or it cannot be passed explicitly to [datastore.py#L1295](https://github.com/projectcalico/libcalico/blob/master/calico_containers/pycalico/datastore.py#L1295)

**Comment by fasaxc** [comment]
@cutwater it'd be difficult to implement such a feature because we wouldn't be able to change the interface prefix for already-created endpoints (so we'd need to keep track of all previous values or handle them specially in felix).  Do you have a particular use-case in mind?

We do use the interface prefix internally, it is set differently in different orchestrators but it's intended to be written by the orchestrator and read by felix.

**Comment by cutwater** [comment]
@fasaxc It would be nice feature to be able to use any prefix except the default one ("cali").

Currently we are testing mixed environment with K8S and OpenStack. And we found that there is a conflict beween interface prefixes set by calico-cni plugin and networking-calico. networking-calico sets `InterfacePrefix` to `tap` which makes impossible to run any k8s pod later.

Currently libcalico creates endpoints with `cali` prefix, since `calico-cni` (v1.3.1) calls  `create_endpoint()` method, but this method doesn't allow to pass endpoint name as a parameter or doesn't read it from etcd. This why `Endpoint` instance is created with default interface prefix, which is `cali`.
At least there might be an option to use custom prefix for all endpoins, not changing it in the runtime. Please refer to my pull request.

**Comment by fasaxc** [comment]
Thanks for explaining the reasoning behind it. 

I'd imagined expanding InterfacePrefix to be a list of values to take care of that use case, so you could set it to `cali,tap` and then felix would allow either to be used.  I prefer that option because it removes the need to support different prefixes in the CNI plugin and to handle the inevitable support requests when an innocent user changes the config parameter and breaks their rig.

Would that solution work for your use case?

**Comment by cutwater** [comment]
@fasaxc It seems in all ways better solution. We considered it as an alternative, but it will be a bit more complicated. I will continue working in this direction.

Should I close this issue as an invalid and open new one related to multiple prefixes in appropriate repository?

**Comment by fasaxc** [comment]
@cutwater Understood; I do think we'd prefer to go down the multiple interfaces route; @neiljerram has a bit of time in plan to help with that (and I think he's set up a call with you to discuss upcoming work).  

> Should I close this issue as an invalid and open new one related to multiple prefixes in appropriate repository?

I think you've already done that (https://github.com/projectcalico/calico/issues/1101).  Thanks!
